// PHASE 4 helper — NOT part of the running app, just a one-off dev script so
// you can load-test the map with more territories than you've generated by
// actually recording runs (see the Phase 4 integration checklist: "Map
// performs acceptably with 50+ dummy territories").
//
// Usage (from the repo root):
//   node backend/scripts/seedTerritories.js [count] [lat] [lng]
//   e.g. node backend/scripts/seedTerritories.js 80 28.6139 77.2090
//
// Reads MONGODB_URI the same way the real server does, so make sure
// backend/.env exists first (cp backend/.env.example backend/.env).

import dotenv from 'dotenv';
dotenv.config({ path: './backend/.env' });

import mongoose from 'mongoose';
import * as turf from '@turf/turf';
import { connectDB } from '../src/config/db.js';
import User from '../src/models/User.js';
import Territory from '../src/models/Territory.js';

// --- Tunables ---
const COUNT = Number(process.argv[2]) || 60;
const CENTER_LAT = Number(process.argv[3]) || 28.6139; // New Delhi — change freely
const CENTER_LNG = Number(process.argv[4]) || 77.209;
const SPREAD_METERS = 3000; // scatter seeded territories within ~3km of center
const MIN_AREA_SQM = 400;
const MAX_AREA_SQM = 8000;

// Used as a fallback color only for territories assigned to the fabricated
// "no real user" owner id (see below) — real users' territories always use
// their actual preferredColor, matching how Phase 3 creates territories.
const FALLBACK_PALETTE = ['#3B82F6', '#34d399', '#f59e0b', '#ef4444', '#a855f7', '#ec4899', '#06b6d4'];

function randomBetween(min, max) {
  return min + Math.random() * (max - min);
}

// Same "organic blob" approach as territoryEngine.js's random-case
// generator, kept intentionally simpler here since these are throwaway test
// fixtures, not real gameplay territories.
function randomBlob(centerLngLat, targetAreaSqm) {
  const numPoints = 8 + Math.floor(Math.random() * 5);
  const baseRadiusM = Math.sqrt(targetAreaSqm / Math.PI);
  const points = [];
  for (let i = 0; i < numPoints; i++) {
    const bearing = (360 * i) / numPoints;
    const r = baseRadiusM * randomBetween(0.7, 1.3);
    const dest = turf.destination(centerLngLat, r / 1000, bearing, { units: 'kilometers' });
    points.push(dest.geometry.coordinates);
  }
  points.push(points[0]); // close the ring
  return turf.polygon([points]);
}

async function main() {
  await connectDB();

  const users = await User.find().limit(20).lean();
  if (users.length === 0) {
    console.warn(
      '[seed] No users found in the DB — seeded territories will reference a ' +
        'fake owner id and show up as "Unknown runner" on the map. Sign up at ' +
        'least one test user first (Phase 1) for a more realistic demo.'
    );
  }
  // Not a real User document — populate('ownerId') will simply resolve this
  // to null on read, which territoryController.js already handles.
  const fallbackOwnerId = new mongoose.Types.ObjectId();

  const docs = [];
  for (let i = 0; i < COUNT; i++) {
    const owner = users.length > 0 ? users[i % users.length] : null;
    const offsetBearing = Math.random() * 360;
    const offsetDist = Math.random() * SPREAD_METERS;
    const center = turf.destination([CENTER_LNG, CENTER_LAT], offsetDist / 1000, offsetBearing, {
      units: 'kilometers',
    });

    const targetAreaSqm = randomBetween(MIN_AREA_SQM, MAX_AREA_SQM);
    const polygon = randomBlob(center.geometry.coordinates, targetAreaSqm);
    const areaSqm = turf.area(polygon);

    docs.push({
      ownerId: owner ? owner._id : fallbackOwnerId,
      geometry: polygon.geometry,
      color: owner ? owner.preferredColor : FALLBACK_PALETTE[i % FALLBACK_PALETTE.length],
      areaSqm,
      shapeType: 'random',
      strength: areaSqm,
    });
  }

  await Territory.insertMany(docs);
  console.log(`[seed] Created ${docs.length} test territories around [${CENTER_LAT}, ${CENTER_LNG}].`);
  await mongoose.disconnect();
}

main().catch((err) => {
  console.error('[seed] Failed:', err);
  process.exit(1);
});
